name: music_player
description: A new Flutter project.



publish_to: 'none' 











version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"







dependencies:
  flutter:
    sdk: flutter
  bloc:
  flutter_bloc:
  equatable:
  http:
  internet_connection_checker:
  connectivity_plus:
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.9
  line_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 
  hive_generator: 
  
  
  
  
  
  flutter_lints: ^1.0.0





flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
